# LastBreathHC Configuration


debug: false

tabMenu:
  refreshTicks: 40
  statsRefreshSeconds: 10

arrowAggro:
  radius: 3.0

anvilCrush:
  radius: 0.75
  mapping:
    COBBLESTONE: GRAVEL
    GRAVEL: SAND

asteroid:
  mobLeashRadius: 16
  impact:
    radius: 2
  spawn:
    minSeconds: 1200
    maxSeconds: 3600
    playerBiasChance: 0.05
    playerBiasRadius: 25000.0
    meteorShowerChance: 0.2
  countdownSeconds: 10
  loot:
    tier1:
      ironIngot:
        min: 6
        max: 19
      goldIngot:
        min: 4
        max: 9
      emerald:
        min: 2
        max: 7
      diamond:
        min: 1
        max: 4
      netheriteScrap:
        min: 1
        max: 1
    tier2:
      ironIngot:
        min: 10
        max: 23
      goldIngot:
        min: 6
        max: 11
      emerald:
        min: 4
        max: 9
      diamond:
        min: 2
        max: 5
      netheriteScrap:
        min: 1
        max: 2
      customItems:
        rebirthStoneChance: 5
        totemOfLifeChance: 5
        gracestoneChance: 1
        enhancedGrindstoneChance: 5
    tier3:
      ironIngot:
        min: 14
        max: 27
      goldIngot:
        min: 8
        max: 13
      emerald:
        min: 6
        max: 11
      diamond:
        min: 3
        max: 6
      netheriteScrap:
        min: 2
        max: 3
      customItems:
        rebirthStoneChance: 5
        totemOfLifeChance: 5
        gracestoneChance: 5
        enhancedGrindstoneChance: 10
    enchantPages:
      tier1Chance: 25
      tier2Chance: 50
      tier3Chance: 75
      extraRolls:
        tier1:
          - 5
        tier2:
          - 15
          - 5
        tier3:
          - 35
          - 20
          - 10
      ids:
        - "lb:quarry"
        - "lb:vein_miner"
        - "lb:auto_pickup"
        - "lb:auto_replant"
        - "lb:tree_feller"
        - "lb:excavator"
        - "lb:fertile_harvest"
        - "lb:smelter_touch"
        - "lb:swift_tiller"
        - "lb:prospector"
  worlds:
    - world
  tiers:
    tier2MinDistance: 10000
    tier3MinDistance: 100000
    effects:
      tier1:
        mobTypes:
          - ZOMBIE
          - SKELETON
        mobType: ZOMBIE
        mobCount: 4
        potionEffects:
          - SPEED:200:0
        aoe:
          enabled: false
          particle: DRAGON_BREATH
          radius: 2.5
          durationTicks: 160
          waitTimeTicks: 0
      tier2:
        mobTypes:
          - ZOMBIE
          - SKELETON
          - BLAZE
          - MAGMA_CUBE
        mobType: BLAZE
        mobCount: 6
        potionEffects:
          - DAMAGE_RESISTANCE:200:0
        aoe:
          enabled: true
          particle: DRAGON_BREATH
          radius: 3.0
          durationTicks: 200
          waitTimeTicks: 0
      tier3:
        mobTypes:
          - ZOMBIE
          - SKELETON
          - WITHER_SKELETON
          - VEX
          - PIGLIN_BRUTE
        mobType: WITHER_SKELETON
        mobCount: 8
        bossTypes:
          - RAVAGER
          - WARDEN
        potionEffects:
          - INCREASE_DAMAGE:200:0
        aoe:
          enabled: true
          particle: DRAGON_BREATH
          radius: 4.0
          durationTicks: 240
          waitTimeTicks: 0

customEnchants:
  rarity: rare
  allowedTools:
    - NETHERITE_PICKAXE
    - NETHERITE_SHOVEL
    - NETHERITE_AXE
    - NETHERITE_HOE
  anvilLevelCost: 30

environment:
  moveCooldownTicks: 20
  distanceScaling:
    checkIntervalTicks: 80
    spawnRadiusBlocks: 6000
    minScale: 0.8
    maxScale: 1.4
  biomes:
    swamp:
      poisonChance: 0.08
      poisonDurationTicks: 100
      poisonAmplifier: 0
      biomes:
        - SWAMP
        - MANGROVE_SWAMP
    desert:
      idleThresholdTicks: 160
      heatTicks: 60
      heatChance: 0.25
      biomes:
        - DESERT
        - BADLANDS
        - ERODED_BADLANDS
        - WOODED_BADLANDS
    mountain:
      knockbackMultiplier: 1.25
      biomes:
        - WINDSWEPT_HILLS
        - WINDSWEPT_GRAVELLY_HILLS
        - WINDSWEPT_FOREST
        - JAGGED_PEAKS
        - FROZEN_PEAKS
        - STONY_PEAKS
        - MEADOW
        - SNOWY_SLOPES
    deepOcean:
      swimSlowMultiplier: 0.6
      drownedDamageMultiplier: 1.35
      biomes:
        - DEEP_OCEAN
        - DEEP_COLD_OCEAN
        - DEEP_FROZEN_OCEAN
        - DEEP_LUKEWARM_OCEAN
